### ISSUE TITLE
not able to login , it work previously but after 20Aug it is stop working.

### ISSUE THREAD

**Issue by foongws** [Terrance/SkPy#140]
This could be due to skype change their login reponse , may be.

here is the error trace.

Traceback (most recent call last):
  File "./rocketchat-bridge.py", line 65, in <module>
    sk=Skype(app_username, app_password,".tokens")
  File "/home/steven/skype/.venv/lib64/python3.8/site-packages/skpy/main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "/home/steven/skype/.venv/lib64/python3.8/site-packages/skpy/conn.py", line 266, in getSkypeToken
    self.liveLogin(user, pwd)
  File "/home/steven/skype/.venv/lib64/python3.8/site-packages/skpy/conn.py", line 368, in liveLogin
    self.tokens["skype"], self.tokenExpiry["skype"] = SkypeLiveAuthProvider(self).auth(user, pwd)
  File "/home/steven/skype/.venv/lib64/python3.8/site-packages/skpy/conn.py", line 542, in auth
    t = self.sendCreds(user, pwd, params)
  File "/home/steven/skype/.venv/lib64/python3.8/site-packages/skpy/conn.py", line 575, in sendCreds
    raise SkypeAuthException(errMsg, loginResp)
skpy.core.SkypeAuthException: ("Couldn't retrieve t field from login response", <Response [200]>)

**Comment by foongws** [comment]
it seem someone reported the same issue. #65
