### ISSUE TITLE
ERROR "skpy.core.SkypeApiException" on Linux

### ISSUE THREAD

**Issue by ae86sen** [Terrance/SkPy#187]
**my code:**
```
def main():
    sk = Skype(skype_user, skype_password,connect=False)  # connect to Skype
    ch = sk.chats.chat(skype_group_id)
    jenkins_to_skype(server, ch)
```
**error:**
```
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/hpc_api_test/workspace/skype_jenkins.py", line 126, in <module>
    main()
  File "/var/lib/jenkins/jobs/hpc_api_test/workspace/skype_jenkins.py", line 121, in main
    ch = sk.chats.chat(skype_group_id)
  File "/usr/local/lib/python3.9/site-packages/skpy/chat.py", line 491, in chat
    json = self.skype.conn("GET", "{0}/users/ME/conversations/{1}".format(self.skype.conn.msgsHost, id),
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 214, in __call__
    self.verifyToken(auth)
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 351, in verifyToken
    self.getRegToken()
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 478, in getRegToken
    self.verifyToken(self.Auth.SkypeToken)
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 348, in verifyToken
    self.getSkypeToken()
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 188, in inner
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 424, in soapLogin
    self.getRegToken()
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 484, in getRegToken
    endpoint.config()
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 1063, in config
    self.conn("PUT", "{0}/users/ME/endpoints/{1}/presenceDocs/messagingService"
  File "/usr/local/lib/python3.9/site-packages/skpy/conn.py", line 237, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('400 response from PUT https://azwcus1-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/{dd69805b-64c8-418d-9b45-4855336f378f}/presenceDocs/messagingService', <Response [400]>)
```
**PS:**
It's ok for me to run this code on Windows,but the above error occurred on Linux.
can you help me?
thanks!

**Comment by Terrance** [comment]
You didn't follow the [issue template](https://github.com/Terrance/SkPy/raw/master/.github/ISSUE_TEMPLATE.md) and didn't include the full HTTP request, so I can't see what the underlying error is.
