### ISSUE TITLE
Introduction of rate limits

### ISSUE THREAD

**Issue by mihalt** [Terrance/SkPy#275]
### Before we start...

- [X] I've searched existing issues, but my request hasn't been submitted yet.
- [X] I've read the documentation, but my request is something new.
- [X] I've checked on [Skype for Web](https://web.skype.com), and the feature I'm requesting does exist there.

### Summary

I plan to introduce https://pyratelimiter.readthedocs.io/en/latest/ to my project to avoid api exceptions. I've checked your section https://skpy.t.allofti.me/background/authentication.html#rate-limiting and don't have any descriptions of exact limits ranges. I understand that you can't give me exact numbers, because you are not a skype developer, but approximate numbers by your expirence would be very helpfull. How much requests should I send in an hour, a day, a week, a month? What limits are pessimistic and should exactly work and what limits are optimistic and just to try? 

### Code sample

```python
.
```

### SkPy version

0.11

### Python version

3.11

**Comment by Terrance** [comment]
> approximate numbers by your expirence would be very helpfull

I have never encountered any rate limits on my own account, so I don't have anything to add here.  Other users regularly sending messages might have a better idea -- consider asking in Discussions.

The current behaviour in SkPy is to raise an exception when any of Skype's APIs return a known rate-limit response, which is as much as can be done here when the APIs themselves do not advertise their limits.

**Comment by mihalt** [comment]
> I have never encountered any rate limits on my own account

You can try to use public vpn and you will meet problems. When I use hosting ip, it is very mad. I think even worse than vpn. I have SkypeApiException first:
```
web-1  | https://login.skype.com:443 "POST /login/microsoft?client_id=578134&redirect_uri=https%3A%2F%2Fweb.skype.com HTTP/11" 200 1906
web-1  | Starting new HTTPS connection (1): api.skype.com:443
web-1  | https://api.skype.com:443 "GET /users/self/profile HTTP/11" 200 432
web-1  | Starting new HTTPS connection (1): client-s.gateway.messenger.live.com:443
web-1  | https://client-s.gateway.messenger.live.com:443 "POST /v1/users/ME/endpoints HTTP/11" 503 981
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 339, in readToken
web-1  |     with open(self.tokenFile, "r") as f:
web-1  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/project/communications/bot_session_tokens/my_account'
web-1  | 
web-1  | During handling of the above exception, another exception occurred:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/main.py", line 67, in __init__
web-1  |     self.conn.readToken()
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 342, in readToken
web-1  |     raise SkypeTokenException("Token file doesn't exist or not readable")
web-1  | skpy.core.SkypeTokenException: Token file doesn't exist or not readable
web-1  | 
web-1  | During handling of the above exception, another exception occurred:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/opt/project/manage.py", line 21, in <module>
web-1  |     main()
web-1  |   File "/opt/project/manage.py", line 17, in main
web-1  |     execute_from_command_line(sys.argv)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
web-1  |     utility.execute()
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
web-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
web-1  |     self.execute(*args, **cmd_options)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
web-1  |     output = self.handle(*args, **options)
web-1  |   File "/opt/project/communications/management/commands/skype_event_loop.py", line 26, in handle
web-1  |     sk = SkypeBot(login, password)
web-1  |   File "/opt/project/communications/skype.py", line 36, in __init__
web-1  |     super().__init__(username, pwd, self.token_file)
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/main.py", line 186, in __init__
web-1  |     super(SkypeEventLoop, self).__init__(user, pwd, tokenFile)
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/main.py", line 69, in __init__
web-1  |     self.conn.getSkypeToken()
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 197, in inner
web-1  |     return method(*args, **kwargs)
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 438, in liveLogin
web-1  |     self.getRegToken()
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 520, in getRegToken
web-1  |     token, expiry, msgsHost, endpoint = SkypeRegistrationTokenProvider(self).auth(self.tokens["skype"])
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 952, in auth
web-1  |     endpointResp = self.conn("POST", "{0}/users/ME/endpoints".format(msgsHost), codes=(200, 201, 404),
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 250, in __call__
web-1  |     raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
web-1  | skpy.core.SkypeApiException: ('503 response from POST https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints', <Response [503]>)
Aborting on container exit...
```

And then if I rerun command it can be due to often requests
```
web-1  | https://login.skype.com:443 "GET /login/oauth/microsoft?client_id=578134&redirect_uri=https%3A%2F%2Fweb.skype.com HTTP/11" 302 0
web-1  | Starting new HTTPS connection (1): login.live.com:443
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 339, in readToken
web-1  |     with open(self.tokenFile, "r") as f:
web-1  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/project/communications/bot_session_tokens/my_account'
web-1  | 
web-1  | During handling of the above exception, another exception occurred:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/main.py", line 67, in __init__
web-1  |     self.conn.readToken()
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 342, in readToken
web-1  |     raise SkypeTokenException("Token file doesn't exist or not readable")
web-1  | skpy.core.SkypeTokenException: Token file doesn't exist or not readable
web-1  | 
web-1  | During handling of the above exception, another exception occurred:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
web-1  |     sock = connection.create_connection(
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
web-1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
web-1  |   File "/usr/local/lib/python3.10/socket.py", line 967, in getaddrinfo
web-1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
web-1  | socket.gaierror: [Errno -3] Temporary failure in name resolution
web-1  | 
web-1  | The above exception was the direct cause of the following exception:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
web-1  |     response = self._make_request(
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
web-1  |     raise new_e
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
web-1  |     self._validate_conn(conn)
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
web-1  |     conn.connect()
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
web-1  |     self.sock = sock = self._new_conn()
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 206, in _new_conn
web-1  |     raise NameResolutionError(self.host, self, e) from e
web-1  | urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f83d9bdc8e0>: Failed to resolve 'login.live.com' ([Errno -3] Temporary failure in name resolution)
web-1  | 
web-1  | The above exception was the direct cause of the following exception:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 589, in send
web-1  |     resp = conn.urlopen(
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
web-1  |     retries = retries.increment(
web-1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
web-1  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
web-1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.live.com', port=443): Max retries exceeded with url: /login.srf?wa=wsignin1.0&rpsnv=162&ct=1729186844&rver=7.5.2156.0&wp=MBI_SSL&wreply=https%3A%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fclient_id%3D578134%26redirect_uri%3Dhttps%253A%252F%252Fweb.skype.com&lc=1033&id=293290&mkt=en-US&psi=skype&lw=1&cobrandid=2befc4b5-19e3-46e8-8347-77317a16a5a5&client_flight=ReservedFlight33%2CReservedFlight67 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f83d9bdc8e0>: Failed to resolve 'login.live.com' ([Errno -3] Temporary failure in name resolution)"))
web-1  | 
web-1  | During handling of the above exception, another exception occurred:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/opt/project/manage.py", line 21, in <module>
web-1  |     main()
web-1  |   File "/opt/project/manage.py", line 17, in main
web-1  |     execute_from_command_line(sys.argv)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
web-1  |     utility.execute()
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
web-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
web-1  |     self.execute(*args, **cmd_options)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
web-1  |     output = self.handle(*args, **options)
web-1  |   File "/opt/project/communications/management/commands/skype_event_loop.py", line 26, in handle
web-1  |     sk = SkypeBot(login, password)
web-1  |   File "/opt/project/communications/skype.py", line 36, in __init__
web-1  |     super().__init__(username, pwd, self.token_file)
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/main.py", line 186, in __init__
web-1  |     super(SkypeEventLoop, self).__init__(user, pwd, tokenFile)
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/main.py", line 69, in __init__
web-1  |     self.conn.getSkypeToken()
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 197, in inner
web-1  |     return method(*args, **kwargs)
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 436, in liveLogin
web-1  |     self.tokens["skype"], self.tokenExpiry["skype"] = SkypeLiveAuthProvider(self).auth(user, pwd)
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 647, in auth
web-1  |     self.getT(user, pwd)
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 676, in getT
web-1  |     stage1Resp = self.check(self.conn("GET", "{0}/oauth/microsoft".format(SkypeConnection.API_LOGIN),
web-1  |   File "/usr/local/lib/python3.10/site-packages/skpy/conn.py", line 239, in __call__
web-1  |     resp = self.sess.request(method, url, headers=headers, **kwargs)
web-1  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
web-1  |     resp = self.send(prep, **send_kwargs)
web-1  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 724, in send
web-1  |     history = [resp for resp in gen]
web-1  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 724, in <listcomp>
web-1  |     history = [resp for resp in gen]
web-1  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 265, in resolve_redirects
web-1  |     resp = self.send(
web-1  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
web-1  |     r = adapter.send(request, **kwargs)
web-1  |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 622, in send
web-1  |     raise ConnectionError(e, request=request)
web-1  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.live.com', port=443): Max retries exceeded with url: /login.srf?wa=wsignin1.0&rpsnv=162&ct=1729186844&rver=7.5.2156.0&wp=MBI_SSL&wreply=https%3A%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fclient_id%3D578134%26redirect_uri%3Dhttps%253A%252F%252Fweb.skype.com&lc=1033&id=293290&mkt=en-US&psi=skype&lw=1&cobrandid=2befc4b5-19e3-46e8-8347-77317a16a5a5&client_flight=ReservedFlight33%2CReservedFlight67 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f83d9bdc8e0>: Failed to resolve 'login.live.com' ([Errno -3] Temporary failure in name resolution)"))
Aborting on container exit...
```
